server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbFetchesDemoDb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  application:
    name: different-db-fetches